# -*- mode: ruby -*-
# vi: set ft=ruby :
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian-squeeze-64"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"
  #config.vm.boot_mode = :gui

  config.vm.customize ["modifyvm", :id, "--memory", 1024]

  # config.vm.network :hostonly, "192.168.33.10"
  config.vm.network :bridged
  #config.vm.forward_port 8080, 8080

end
