# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian-squeeze-64"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"

  #config.vm.boot_mode = :gui

  # config.vm.network :hostonly, "192.168.33.10"
  #config.vm.host_name = 'chef-server'
  config.vm.network :bridged, :mac => '080027B2053A'
  #config.vm.base_mac = '080027B2053A'

  config.vm.forward_port 4040, 4040
  config.vm.forward_port 4000, 4000

  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["../my-recipes/chef-server-cookbooks", "../my-recipes/shared-cookbooks"]
     chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
     chef.add_role "chef_server"

  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
   end

end
