Vagrant::Config.run do |config|
  config.vm.box = "debian-squeeze-64"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"
  #config.vm.boot_mode = :gui

  config.vm.share_folder "Documents", "~/Documents", "~/Documents"
  config.vm.share_folder "Dropbox", "~/Dropbox", "~/Dropbox"
  config.vm.share_folder "kaize", "~/kaize", "~/kaize"

  config.vm.customize ["modifyvm", :id, "--memory", 512]

  config.vm.network :bridged
end

