# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian-squeeze-64"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"

#   config.vm.boot_mode = :gui

  #config.vm.network :hostonly, "192.168.1.19"

  config.vm.network :bridged

  config.vm.forward_port 80, 8000


  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["../my-recipes/cookbooks", "../my-recipes/kaize-cookbooks"]
     chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
     chef.add_recipe "mybook"
     chef.add_role "django_application"

  #   chef.json = { :mysql_password => "foo" }
   end

end
